---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: prepare
  image: webhippie/ruby:latest
  pull: always
  commands:
  - bundle install --path=gems --retry=5 --jobs=5

- name: rubocop
  image: webhippie/ruby:latest
  pull: always
  environment:
    CODACY_PROJECT_TOKEN:
      from_secret: codacy_token
  commands:
  - bundle exec rake rubocop

- name: test
  image: webhippie/ruby:latest
  pull: always
  environment:
    CODACY_PROJECT_TOKEN:
      from_secret: codacy_token
  commands:
  - bundle exec rake spec

- name: release
  image: plugins/rubygems:1
  pull: always
  settings:
    gemname: umschlag
    gemspec: umschlag.gemspec
    api_key:
      from_secret: rubygems_api_key
  when:
    event:
    - tag

- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    event:
    - push
    - tag
    status:
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
