# -*- encoding: utf-8 -*-

=begin
#Umschlag OpenAPI

#API definition for Umschlag

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

$LOAD_PATH.push File.expand_path('../lib', __FILE__)
require 'umschlag/version'

Gem::Specification.new do |s|
  s.name = 'umschlag'
  s.version = Umschlag::VERSION
  s.date = Time.now.utc.strftime('%F')
  s.platform = Gem::Platform::RUBY

  s.authors = ['Thomas Boerger']
  s.email = ['thomas@webhippie.de']
  s.homepage = 'https://github.com/umschlag/umschlag-ruby'
  s.summary = 'Docker distribution management system'
  s.description = 'A client library for the Umschlag API generated from the OpenAPI spec.'
  s.license = 'Apache-2.0'

  s.files = ['CHANGELOG.md', 'CONTRIBUTING.md', 'DCO', 'README.md', 'LICENSE']
  s.files += Dir.glob('lib/**/*')

  s.test_files = Dir.glob('spec/**/*')

  s.executables = []
  s.require_paths = ['lib']

  s.required_ruby_version = '>= 2.5.0'

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'rubocop', '~> 0.66', '>= 0.66.0'
  s.add_development_dependency 'vcr', '~> 3.0', '>= 3.0.1'
  s.add_development_dependency 'webmock', '~> 1.24', '>= 1.24.3'
end
