=begin
#Umschlag OpenAPI

#API definition for Umschlag

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Umschlag::ProfileApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProfileApi' do
  before do
    # run before each test
    @api_instance = Umschlag::ProfileApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProfileApi' do
    it 'should create an instance of ProfileApi' do
      expect(@api_instance).to be_instance_of(Umschlag::ProfileApi)
    end
  end

  # unit tests for show_profile
  # Retrieve an unlimited auth token
  # @param [Hash] opts the optional parameters
  # @return [Profile]
  describe 'show_profile test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for token_profile
  # Retrieve an unlimited auth token
  # @param [Hash] opts the optional parameters
  # @return [AuthToken]
  describe 'token_profile test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_profile
  # Retrieve an unlimited auth token
  # @param profile The profile data to update
  # @param [Hash] opts the optional parameters
  # @return [Profile]
  describe 'update_profile test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
