=begin
#Umschlag OpenAPI

#API definition for Umschlag

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

# Common files
require 'umschlag/api_client'
require 'umschlag/api_error'
require 'umschlag/version'
require 'umschlag/configuration'

# Models
require 'umschlag/models/auth_login'
require 'umschlag/models/auth_token'
require 'umschlag/models/auth_verify'
require 'umschlag/models/general_error'
require 'umschlag/models/profile'
require 'umschlag/models/team'
require 'umschlag/models/team_user'
require 'umschlag/models/team_user_params'
require 'umschlag/models/user'
require 'umschlag/models/user_team_params'
require 'umschlag/models/validation_error'
require 'umschlag/models/validation_error_errors'

# APIs
require 'umschlag/api/auth_api'
require 'umschlag/api/profile_api'
require 'umschlag/api/team_api'
require 'umschlag/api/user_api'

module Umschlag
  class << self
    # Customize default settings for the SDK using block.
    #   Umschlag.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
